name: 'Setup Forge Development Environment'
description: 'Sets up Foundry, Node.js, and pnpm for Forge projects'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '18'
  
  pnpm-version:
    description: 'pnpm version to install'
    required: false
    default: '9.0.6'
  
  foundry-version:
    description: 'Foundry version to install'
    required: false
    default: 'stable'

runs:
  using: 'composite'
  steps:
    - name: "Install Foundry"
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
      with:
        version: ${{ inputs.foundry-version }}

    - name: "Install NodeJS"
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: "Disable pnpm strict version check"
      shell: bash
      run: pnpm config set package-manager-strict false
