name: "Simulate modules using the modulekit"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      foundry-fuzz-runs:
        default: 1000
        required: false
        type: "number"

      foundry-invariant-depth:
        default: 20
        required: false
        type: "number"

      foundry-invariant-runs:
        default: 20
        required: false
        type: "number"

      foundry-profile:
        default: "default"
        required: false
        type: "string"

      fuzz-seed:
        default: false
        required: false
        type: boolean

      match-path:
        required: true
        type: "string"

      name:
        default: "Forge"
        required: false
        type: "string"

      restore-cache:
        default: true
        required: false
        type: boolean

      foundry-gas-limit:
        default: "18446744073709551615"
        required: false
        type: "string"

      foundry-memory-limit:
        default: 2147483648
        required: false
        type: "number"

      foundry-verbosity:
        default: 3
        required: false
        type: "number"

    secrets:
      MAINNET_RPC_URL:
        required: false
      TESTNET_RPC_URL:
        required: false
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  forge-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: "Setup github access for private dependencies"
        uses: rhinestonewtf/reusable-workflows/.github/actions/setup-gh-access@main
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
        with:
          version: stable

      - name: "Install NodeJS"
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        with:
          version: 9.0.6
          run_install: false

      - name: "Disable pnpm strict version check"
        run: pnpm config set package-manager-strict false

      - name: "Restore the cached build and the node modules"
        if: ${{ inputs.restore-cache }}
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: ${{ inputs.cache-path }}

      - name: "Install the Node.js dependencies"
        run: "pnpm install"

      - name: "Test account: default"
        run: 'ACCOUNT_TYPE=DEFAULT forge test --match-path "${{ inputs.match-path }}"'
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          FOUNDRY_VERBOSITY: ${{ inputs.foundry-verbosity }}
          FOUNDRY_GAS_LIMIT: ${{ inputs.foundry-gas-limit }}
          FOUNDRY_MEMORY_LIMIT: ${{ inputs.foundry-memory-limit }}

      - name: "Test account: Safe"
        run: 'ACCOUNT_TYPE=SAFE forge test --match-path "${{ inputs.match-path }}"'
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          FOUNDRY_VERBOSITY: ${{ inputs.foundry-verbosity }}
          FOUNDRY_GAS_LIMIT: ${{ inputs.foundry-gas-limit }}
          FOUNDRY_MEMORY_LIMIT: ${{ inputs.foundry-memory-limit }}

      - name: "Test account: Kernel"
        run: 'ACCOUNT_TYPE=KERNEL forge test --match-path "${{ inputs.match-path }}"'
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          FOUNDRY_VERBOSITY: ${{ inputs.foundry-verbosity }}
          FOUNDRY_GAS_LIMIT: ${{ inputs.foundry-gas-limit }}
          FOUNDRY_MEMORY_LIMIT: ${{ inputs.foundry-memory-limit }}

      - name: "Test account: NEXUS"
        run: 'ACCOUNT_TYPE=NEXUS forge test --match-path "${{ inputs.match-path }}"'
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          FOUNDRY_VERBOSITY: ${{ inputs.foundry-verbosity }}
          FOUNDRY_GAS_LIMIT: ${{ inputs.foundry-gas-limit }}
          FOUNDRY_MEMORY_LIMIT: ${{ inputs.foundry-memory-limit }}

      - name: "Add summary"
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
