name: "Build a Forge project"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      save-cache:
        default: true
        required: false
        type: boolean

    secrets:
      DEPLOY_KEYS:
        required: false

jobs:
  forge-build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: Set up SSH keys for private dependencies
        run: |
          if [ -n "${DEPLOY_KEYS}" ]; then
            echo "SSH keys found, setting up..."

            echo "$DEPLOY_KEYS" > id_rsa
            chmod 600 id_rsa

            eval "$(ssh-agent -s)"
            ssh-add id_rsa || true

            awk '/^-----BEGIN OPENSSH PRIVATE KEY-----/ {
                file = "key_" ++count
            }
            { print > file }
            END {
                for (i = 1; i <= count; i++) {
                    system("chmod 600 key_" i)
                    system("ssh-add key_" i)
                }
            }' id_rsa

            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            echo "GIT_SSH_COMMAND=\"ssh -i $(pwd)/id_rsa -o IdentitiesOnly=yes\"" >> $GITHUB_ENV
          else
            echo "No SSH keys provided. Skipping."
          fi
        env:
          DEPLOY_KEYS: ${{ secrets.DEPLOY_KEYS }}


      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1.2.0"
        with:
          version: stable

      - name: "Install NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.0.6
          run_install: false

      - name: "Install the Node.js dependencies"
        run: "pnpm install"

      - name: "Show the Forge config"
        run: "forge config"

      - name: "Build the production contracts"
        run: "forge build"

      - name: "Cache node__odules"
        if: ${{ inputs.save-cache }}
        uses: "actions/cache/save@v4"
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: node_modules

      - name: "Cache the contracts and the node modules so that they can be re-used by the other jobs"
        if: ${{ inputs.save-cache }}
        uses: "actions/cache/save@v4"
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: out

      - name: "Add summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
