name: "Prepare Artifacts"

on:
  workflow_call:
    secrets:
      DEPLOY_KEYS:
        required: false

jobs:
  forge-artifacts:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Setup SSH keys for private dependencies"
        uses: ./.github/actions/setup-ssh-keys
        with:
          deploy-keys: ${{ secrets.DEPLOY_KEYS }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1.2.0"
        with:
          version: stable

      - name: "Install NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.0.6
          run_install: false

      - name: "Disable pnpm strict version check"
        run: pnpm config set package-manager-strict false

      - name: "Install the Node.js dependencies"
        run: "pnpm install"

      - name: "Prepare the contract artifacts"
        run: "./shell/prepare-artifacts.sh"

      - name: "Store the contract artifacts in CI"
        id: upload-artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: "contract-artifacts"
          path: "artifacts"

      - name: "Push Artifacts to repo"
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] contract artifacts"

      - name: "Add summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
          echo "## Artifact Link" >> $GITHUB_STEP_SUMMARY
          echo "Download artifacts: ${{ steps.upload-artifact.outputs.artifact-url }}" >> $GITHUB_STEP_SUMMARY
