name: "Test with pnpm"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      restore-cache:
        default: true
        required: false
        type: boolean

    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: "Setup github access for private dependencies"
        uses: rhinestonewtf/reusable-workflows/.github/actions/setup-gh-access@main
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: "Disable pnpm strict version check"
        run: pnpm config set package-manager-strict false

      - name: "Restore the cached build and the node modules"
        if: ${{ inputs.restore-cache }}
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: ${{ inputs.cache-path }}

      - name: "Install the Node.js dependencies"
        run: "pnpm install"

      - name: Run tests
        run: pnpm test
